<img src="https://img-blog.csdn.net/2018092916042238?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2thaWVuMTIyNg==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70" style="width:1000px;height:500px;float:left">

<font color=#8552a1 size= 6>
  随机生成规定范围内的数组 
</font>

<hr class="docutils" />

<blockquote><p><font size= 4>
numpy.random.randint(low, high=None, size=None, dtype='l')
    </font>
</blockquote>

<table style="width:100%;border-collapse:collapse;background-color:white;">
    <tr style="background-color:rgba(30, 200,100, 0.8)" >
      <th> <font size= 5> Example  </font></th>
    </tr>
<table>

In [2]:
import numpy as np
np.random.randint(2, size=10)

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 0])

In [3]:
np.random.randint(5, size=(2, 4))

array([[0, 2, 0, 1],
       [4, 2, 2, 4]])

In [18]:
np.random.randint(2,5)

2

<font color=#8552a1 size= 6>
  逐位比较数组取其大者 
</font>

<hr class="docutils" />

<blockquote><p><font size= 4>
np.maximum：(X, Y, out=None) 
    </font>
</blockquote>

<table style="width:100%;border-collapse:collapse;background-color:white;">
    <tr style="background-color:rgba(30, 200,100, 0.8)" >
      <th> <font size= 5> Example  </font></th>
    </tr>
<table>

In [19]:
np.maximum([-2, -1, 0, 1, 2], 0)

array([0, 0, 0, 1, 2])

In [20]:
np.maximum([-2, -1, 0, 1, 2], [0, -2, 1, 3, 2])

array([ 0, -1,  1,  3,  2])

<font color=#8552a1 size= 6>
  将数组或矩阵中的元素从小到大排列，提取其对应的index(索引)输出
</font>

<hr class="docutils" />

<blockquote><p><font size= 4>
numpy.argsort(a, axis=-1, kind='quicksort', order=None)
    </font>
</blockquote>

<table style="width:100%;border-collapse:collapse;background-color:white;">
    <tr style="background-color:rgba(30, 200,100, 0.8)" >
      <th> <font size= 5> Example  </font></th>
    </tr>
<table>


In [6]:
import numpy as np
x=np.array([1,4,3,-1,6,9])
np.argsort(x,axis=-1)

array([3, 0, 2, 1, 4, 5])

<font color=#8552a1 size= 6>
  查看数组中成员的真假
</font>

<hr class="docutils" />

<blockquote><p><font size= 4>
numpy.isnan()
    </font>
</blockquote>

<table style="width:100%;border-collapse:collapse;background-color:white;">
    <tr style="background-color:rgba(30, 200,100, 0.8)" >
      <th> <font size= 5> Example  </font></th>
    </tr>
<table>

In [3]:
import numpy as np
y = [np.log(-1.),1.,np.log(0)]
np.isnan(y)

/home/zhengyuanbo/.local/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  
/home/zhengyuanbo/.local/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([ True, False, False])